pipeline {
    agent any

    environment {
        IMAGE_NAME = "jenkins-python-demo"
        CONTAINER_NAME = "python-container"
    }

    stages {
        stage('Clone Repository') {
            steps {
               git branch: 'main', url: 'https://github.com/Sukanthi2000/Assignment_Sukanthi.git'
            }
        }

        stage('Build Python App') {
            steps {
                sh 'python3 -m pip install -r Assignment_1/requirements.txt'

            }
        }

        stage('Test') {
            steps {
                sh 'python -m pytest Assignment_1/test/ -v'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t jenkins-python-demo ./Assignment_1'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh """
                docker stop $CONTAINER_NAME || true
                docker rm $CONTAINER_NAME || true
                docker run -d --name $CONTAINER_NAME -p 5000:5000 $IMAGE_NAME
                """
            }
        }
    }

    post {
        success {
            echo '✅ Python App built and deployed successfully!'
        }
        failure {
            echo '❌ Build failed. Check logs.'
        }
    }
}
